services:
  broker:
    image: "bitnamilegacy/rabbitmq:3.13.3"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_PLUGINS: "rabbitmq_management rabbitmq_mqtt"
      RABBITMQ_USERNAME: "intersect_username"
      RABBITMQ_PASSWORD: "intersect_password"
      RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS: "yes"

  nsdf-storage-service:
    build: .
    volumes:
      - ./local-docker-conf.json:/app/local-conf.json:ro
    depends_on:
      - broker
