services:
  broker:
    image: "bitnamilegacy/rabbitmq:3.13.3"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_PLUGINS: "rabbitmq_management rabbitmq_mqtt"
      RABBITMQ_USERNAME: "intersect_username"
      RABBITMQ_PASSWORD: "intersect_password"
      RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS: "yes"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      retries: 5
      start_period: 15s
      timeout: 10s

  nsdf-storage-service:
    build: .
    ports:
      - "8059:8059"
    volumes:
      - ./local-docker-conf.json:/app/local-conf.json:ro
      - nsdf-storage-data:/app/data
    depends_on:
      broker:
        condition: service_healthy

volumes:
  nsdf-storage-data:
