services:
  broker:
    image: "bitnamilegacy/rabbitmq:3.13.3"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_PLUGINS: "rabbitmq_management rabbitmq_mqtt"
      RABBITMQ_USERNAME: "intersect_username"
      RABBITMQ_PASSWORD: "intersect_password"
      RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS: "yes"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      retries: 5
      start_period: 15s
      timeout: 10s

  nsdf-storage-service:
    build: .
    ports:
      - "8059:8059"
    environment:
      NSDF_STORAGE_SERVICE_CONFIG_JSON: |
        {
          "intersect": {
            "brokers": [
              {
                "username": "intersect_username",
                "password": "intersect_password",
                "host": "broker",
                "port": 5672,
                "protocol": "amqp0.9.1"
              }
            ]
          },
          "intersect-hierarchy": {
            "organization": "chess",
            "facility": "chess-facility",
            "system": "storage-system",
            "subsystem": "storage-subsystem",
            "service": "nsdf-storage-service"
          },
          "s3": {
            "aws_access_key_id": "",
            "aws_secret_access_key": "",
            "endpoint_url": "",
            "bucket": "",
            "data_dir": "/app/data"
          },
          "dashboard": {
            "enabled": true,
            "host": "0.0.0.0",
            "port": 8059,
            "route": "/dashboard",
            "grid_size": null,
            "grid_bounds": null
          },
          "persistence": {
            "show_unpersisted_updates": true,
            "retry_interval_seconds": 5,
            "max_retry_interval_seconds": 60
          }
        }
    volumes:
      - nsdf-storage-data:/app/data
    depends_on:
      broker:
        condition: service_healthy

volumes:
  nsdf-storage-data:
